### ISSUE TITLE
GdsWriter recursive write cells

### ISSUE THREAD

**Issue by cecial** [heitzmann/gdstk#102]
lib = gdstk.read_gds(some_gds_file)
writer = gdstk.GdsWriter("new.gds")
writer.writer(lib.cells[0])
writer.close()

if lib.cells[0] contains a lots of references, is it possible that also write these references cell (and references of references...) to new.gds, with a flag like "recursive=1" for writer method?

**Comment by heitzmann** [comment]
@cecial GdsWriter is supposed to be a very low-level API for incrementally creating particularly large files.
Doing a blind recursion could insert a cell more than once in the final file, so some bookkeeping is required, which is out of the scope of this API.

For your example, recursion should be easy enough to implement at user level with [`Cell.dependencies`](https://heitzmann.github.io/gdstk/library/gdstk.Cell.html#gdstk.Cell.dependencies):
```python
lib = gdstk.read_gds(some_gds_file)
writer = gdstk.GdsWriter("new.gds")
writer.write(lib.cells[0], *lib.cells[0].dependencies(True))
writer.close()
```

**Comment by cecial** [comment]
> 

Hi, Heitzmann
this implementation also meets my request, thanks!
