### ISSUE TITLE
specifying ZLIB paths throught environment variables ZLIB_INCLUDE_DIRS, ZLIB_LIBRARIES does not work

### ISSUE THREAD

**Issue by dtzikas** [heitzmann/gdstk#107]
there seems to be a bug in CMakeLists.txt that does not read the specified enviromnent variables correctly.
> set(ZLIB_INCLUDE_DIRS ENV{ZLIB_INCLUDE_DIRS})
 should be 
> set(ZLIB_INCLUDE_DIRS **$**ENV{ZLIB_INCLUDE_DIRS})

I could submit a pull request to fix this, but I was thinking it might be preferable to completely discard these variables. Since CMake's find_package already has a similar mechanism to specify paths (cmake -DZLIB_ROOT=%path%), do you think it makes sense to eliminate variables ZLIB_LIBRARIES and ZLIB_INCLUDE_DIRS?

Thank you

**Comment by heitzmann** [comment]
This was changed due to #73. To be honest, I don't use any of this code on linux and my CMake knowledge is limited. That said, I believe leaving the variables there doesn't hurt and helps when the build relies on the environment variable, right?

The change to `$ENV` is needed, though!
