### ISSUE TITLE
Different custom ends on either side of RobustPath/FlexPath

### ISSUE THREAD

**Issue by larchen** [heitzmann/gdstk#111]
When specifying custom ends, is it possible to specify a different shape for the two ends of a trace?

From [this](https://heitzmann.github.io/gdstk/how-tos.html#connection-pads) example, it seems like the same function is used on both sides.

**Comment by heitzmann** [comment]
That's correct, the same function will be used on both sides. Maybe your function can give 2 different shapes based on the position on the layout or the number of times its been called?
