### ISSUE TITLE
Problems due to the Lack of constructor of Array object

### ISSUE THREAD

**Issue by saurabh64sant** [heitzmann/gdstk#115]
Hello, 
I was trying to read gdsii file using the code below.
`int mail () {
	double units, precision;
	gds_units ("coupler.gds", units, precision);
  Library lib1 = read_gds ("coupler.gds", units, precision, NULL, NULL);
  for (uint64_t i = 0; i < lib1.cell_array.count; i++) {
          Cell* cell = lib1.cell_array[i];
          
          if (cell == NULL) continue;
          Array<Polygon*> allPoly;
          cell->get_polygons (true, false, -1, true, 32, allPoly);
  }
}`

I was always getting segmentation fault. After hours of debugging I realised, that Array<Polygon*> struct does not have a default constructor. Hence Array::items object which stores address, takes random value during execution. This causes problems with Array::ensure_slots () and many other functions. My request is to add constructors to Array object in file "array.h" as follows:

`    Array () {capacity = 0; count = 0; items = NULL;}
    Array (int i) {
        if (i <= 0) {
                capacity = 0; count = 0; items = NULL;
        } else {
                items = NULL;
                this->ensure_slots (i);
        };
    }
    Array (uint64_t cap, uint64_t c, T* it) { capacity = cap; count = c; items = it;}
`
Adding the above code solves my problem.

Best regards
Saurabh

**Comment by heitzmann** [comment]
Thanks for the feedback, but this is the intended behavior: https://heitzmann.github.io/gdstk/reference_cpp.html

By the way, please read the docs; 10 min reading this page would have saved you “hours of debugging”.
