### ISSUE TITLE
pip install gdstk on Windows and CentOs?

### ISSUE THREAD

**Issue by joamatab** [heitzmann/gdstk#124]
Hi Lucas,

How can we `pip install gdstk` on Windows?

![image](https://user-images.githubusercontent.com/4514346/201229524-b5a18b33-8695-4d23-a62a-4c9100b1582f.png)

I think you need to trigger a release for the PyPi GitHub action

@skandanC
@pwuertz

**Comment by joamatab** [comment]
Same issue happens on CentOs

![image](https://user-images.githubusercontent.com/4514346/201390939-ded8f8d5-065d-485e-bcd0-c3e9fe2913f0.png)

**Comment by joamatab** [comment]
#125  includes a fix for this

**Comment by SkandanC** [comment]
Running the command that's on `pypi-packages.yml` for windows: 
![image](https://user-images.githubusercontent.com/100642027/201403394-bc7f9430-93b8-45d5-9b8a-6275666da606.png)

chucks out this error:
![image](https://user-images.githubusercontent.com/100642027/201403428-4a20b5f4-d024-4a1c-a618-31edf45e8e16.png)

Modifying the compiler version number puts out this error:
![image](https://user-images.githubusercontent.com/100642027/201403476-9062f3e8-6c98-4093-97d4-4bb7b5bcf5db.png)

**Comment by joamatab** [comment]
I was hoping the windows image on github actions has zlib installed

@basnijholt

**Comment by pwuertz** [comment]
@joamatab

> How can we pip install gdstk on Windows?

The CI script for producing Windows wheels is ready, but there hasn't been a release (new version tag) to trigger it yet.
So as soon as a new version is tagged we should be able to pip install gdstk.

> Same issue happens on CentOs

As the project readme says, on Linux you can install gdstk as a conda package or build it from source. Building from source is easy on Linux, just install the listed requirements using your preferred package manager. The error message you posted suggests that "cmake" is missing on your system.

**Comment by pwuertz** [comment]
@SkandanC

A few lines prior to the conan install command you found in `pypi-packages.yml`, note that MSVC is being selected as the default compiler, which is the compiler the version-option I added was intended for.

On your system conan can't find MSVC (not installed or environment not set up) and found GCC/mingw as a fallback. Usually, this is not the toolchain you'd use to build DLLs with, since the official Python binaries are built with MSVC.

I don't know if ABI compatibility is still an issue nowadays, but if GCC is the toolchain you want you can still give it a try. The next error you encountered just states that there are no pre-built conan packages for your toolchain. You can tell conan to build zlib from source by adding the `--build=missing` option on install.

**Comment by joamatab** [comment]
Im trying to get the wheels build using CICD
https://github.com/pypa/cibuildwheel

**Comment by joamatab** [comment]
the wheels work now for windows and MacOs

![image](https://user-images.githubusercontent.com/4514346/201569053-9a011397-dce0-4028-93d6-dd4602f8ead1.png)


https://pypi.org/project/gdstk/#files

CentOs still not working yet

**Comment by joamatab** [comment]
For CentOs to work the main issue we were getting is the zlib being older than 1.2.9

**Comment by tvt173** [comment]
> For CentOs to work the main issue we were getting is the zlib being older than 1.2.9

so, i would expect it should still work on CentOS with conda, right? but not pip? still a very nice improvement to have it working for windows and mac!

**Comment by joamatab** [comment]
yes, with conda it works on every OS

**Comment by pwuertz** [comment]
@joamatab You might be able to use the same strategy I used for building gdstk on Windows CI:

- (pip) install conan
- Let conan fetch or build a static zlib of given version + create a cmake toolchain file
- Let pip install gdstk from source, with the cmake toolchain file specified via ENV

-> The gdstk cmake build process should be able to see the new zlib version

**Comment by heitzmann** [comment]
With the recent release automation introduced by @joamatab, the package's available through PyPI. I'll consider this issue closed for now.
