### ISSUE TITLE
How can we get gdstk.points

### ISSUE THREAD

**Issue by joamatab** [heitzmann/gdstk#132]
```
import gdstk

p = gdstk.FlexPath(width=0.5, points=[(-0.1, 0), (+0.1, 0)])
print(p.points)
```

returns
```
AttributeError: 'gdstk.FlexPath' object has no attribute 'points'
```

**Comment by ottumm** [comment]
@joamatab I'm not sure if this is what you're asking, but if you want to get the polygonal representation of the path, you can do that with `p.to_polygons()`.

The input parameters `points` and `width` [don't appear to be exposed as attributes](https://heitzmann.github.io/gdstk/geometry/gdstk.FlexPath.html#gdstk-flexpath).

**Comment by joamatab** [comment]
Thank you Mike, yes, I'm using that trick too

How could expose points and width directly from Polygon?

**Comment by ottumm** [comment]
Depending on your use case, you may be able to use `FlexPath.spin()`, `FlexPath.path_spines()`, and `FlexPath.widths()` to do what you want. Note that `FlexPath` objects can be quite complicated because each object can consist of multiple paths.

**Comment by heitzmann** [comment]
@joamatab: What @ottumm said is probably your best option indeed!
