### ISSUE TITLE
unclear utility of `get_property` and `set_property`

### ISSUE THREAD

**Issue by nmz787-intel** [heitzmann/gdstk#141]
I was trying to get the layer and datatype for a given polygon, and saw `get_property` and `set_property` methods. It was not clear the utility, or legal argument strings, allowed for passing to `get_property` or `set_property`.

I tried `get_property('layer')` which returned `None`.

I then found `myPolygon.layer` yielded the desired data.

All I am asking for is clarification on what these two methods do, how they're useful (i.e. for custom user-based information storage) and whether they are saved/loaded to/from GDS and/or OASIS.

Thanks!

**Comment by nmz787-intel** [comment]
Ok, I read the docs before coming here, and I'm actually asking for clarification/update over there. With my experiment, found there's not apparently any pre-populated data there. I am unfamiliar with the industry/published file format specs, so maybe that's where my ignorance stems from, but adding a comment to those methods like "these get/set methods can be used for custom metadata". I'm not sure how to better word it, sorry (maybe add in the word persistent, or something?)! But I get the idea now, thanks!

**Comment by heitzmann** [comment]
There isn't really a lot more to say. Each software might use those properties for different purposes, or completely ignore them. I put a note in the docs, though.
