### ISSUE TITLE
Latest gdstk version whl to compatible with a specific numpy version

### ISSUE THREAD

**Issue by phylove01** [heitzmann/gdstk#143]
Hi, heizmann,

I am trying to install gdstk into my offline environment. I succeeded in installing latest version whl file(0.9.35) through pip, but I have an error message "RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xe". Since, I have to use a specific version of numpy(1.20.1) due to the other libraries, could you share the latest version whl file to compatible with numpy 1.20.1? I tried all the other source files, gdstk-*.tar.gz on pypi, but I failed to install those through pip and setuptools because of the other dependency in my offline environment. Please help me to use gdstk!

**Comment by joamatab** [comment]
Hi Lucas,

gdstk is failing in colab
![image](https://user-images.githubusercontent.com/4514346/215675896-9373ab41-6d80-472d-918b-3131d2db3f8e.png)


@proppy
@heitzmann 
@lucas-flexcompute

**Comment by proppy** [comment]
one possible workaround that we used for https://github.com/chipsalliance/silicon-notebooks/issues/30, is to do:
```
python -m pip install --no-binary gdstk gdstk
```
to force recompiling gdstk against the current environment.

**Comment by joamatab** [comment]
Hi Lucas,

most users using colab are not able to install gdstk

I also tried upgrading numpy before but it does not worl

![image](https://user-images.githubusercontent.com/4514346/218125159-64bcd588-9e11-444e-9a70-7cfbd210273d.png)

**Comment by heitzmann** [comment]
I've just found out this package: https://pypi.org/project/oldest-supported-numpy/ which might be what we need to ensure the most compatible version of numpy possible, instead of using the latest available in each CI image. I'll try to set it up in the next few days to see how it goes. Maybe it will solve this issue in a more user-friendly way…

**Comment by heitzmann** [comment]
Looks like it works now on release 0.9.37.

![screenshot](https://user-images.githubusercontent.com/5938451/218324331-517b53d4-669b-4382-8192-32c003968210.png)

**Comment by joamatab** [comment]
Yay! thank you Lucas!

works great on colab now!

![image](https://user-images.githubusercontent.com/4514346/218324954-43c35671-17a5-4040-8898-1adcc4d3c355.png)
