### ISSUE TITLE
How to get flattened version of polygons and labels?

### ISSUE THREAD

**Issue by songlinsaloman** [heitzmann/gdstk#145]
I need to process a flattened gds, that is, polygons are merged in top cell with global coordinates (not partial polygons in local cell local coordinates). I also need to get labels in top. Could you kindly tell me how to do that with the code? Can't thank you too much!

Saloman Lin

**Comment by heitzmann** [comment]
@songlinsaloman, if you already have the top-level cell (find it through [`Library.top_level()`](https://heitzmann.github.io/gdstk/library/gdstk.Library.html#gdstk.Library.top_level)) you can use [`Cell.get_polygons`](https://heitzmann.github.io/gdstk/library/gdstk.Cell.html#gdstk.Cell.get_polygons) and [`Cell.get_labels`](https://heitzmann.github.io/gdstk/library/gdstk.Cell.html#gdstk.Cell.get_labels) to retrieve both. You could also flatten the cell and query the elements afterwards.
