### ISSUE TITLE
Published wheel overwrites locally built code in MacOS 3.10 CI build

### ISSUE THREAD

**Issue by jatoben** [heitzmann/gdstk#149]
Recently, the MacOS 3.10 CI build seems to be [overwriting the locally built version of gdstk with a wheel pulled from PyPI](https://github.com/heitzmann/gdstk/actions/runs/4156963335/jobs/7191110945#step:6:386):

```
Installed /Users/runner/.local/lib/python3.10/site-packages/gdstk-0.9.36-py3.10-macosx-11.7-x86_64.egg
Processing dependencies for gdstk==0.9.36
Searching for gdstk==0.9.36
Reading https://pypi.org/simple/gdstk/
Downloading https://files.pythonhosted.org/packages/bd/a3/3ae2c9943a7b84cee019c43cff64ff09d5719ff50902129da79498de7560/gdstk-0.9.36-cp310-cp310-macosx_10_9_x86_64.whl#sha256=8ba7bd65bd77a25947ce1c06a835d64d7d92a5fad28eef32d68fc1faee2685f1
Best match: gdstk 0.9.36
Processing gdstk-0.9.36-cp310-cp310-macosx_10_9_x86_64.whl
removing '/Users/runner/.local/lib/python3.10/site-packages/gdstk-0.9.36-py3.10-macosx-11.7-x86_64.egg' (and everything under it)
Installing gdstk-0.9.36-cp310-cp310-macosx_10_9_x86_64.whl to /Users/runner/.local/lib/python3.10/site-packages
gdstk 0.9.36 is already the active version in easy-install.pth
```

I noticed this while working on a project that uses gdstk; the tests failed because they did not include my local modifications.

Locally, I fixed this by changing `python setup.py install` in the `testing.yml` file to `pip install .`, which builds a wheel and then installs it. Doing so also prevents [this deprecation warning](https://github.com/heitzmann/gdstk/actions/runs/4156963335/jobs/7191110945#step:6:13):

```
SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
```

I am not sure if that change is appropriate here since I have not followed the recent packaging changes, but wanted to bring the issue to your attention.

**Comment by heitzmann** [comment]
I believe that's expected because pip will prefer precompiled binaries when available over source distributions, and we've increased the number of available packages lately.

If I'm not mistaken, there's a flag to avoid using the binary from PyPI, if you want to compile locally.
