### ISSUE TITLE
cell.get_polygons(copy=True/False)

### ISSUE THREAD

**Issue by albe-jj** [heitzmann/gdstk#157]
It would be nice to be able to use the cell.get_polygon to get the polygons of that cell not just a copy of it. 
In the case for example I would just want to do some operation to the polygons in a certain layer of my main cell. 

Would be a handy alternative to the less compact `[pol for pol in main_cell.polygons if pol.layer==target_layer]`.

**Comment by heitzmann** [comment]
@albe-jj Thanks for the suggestion, but that would mek `get_polygons` even more complicated than it already is. Plus, the addition of an argument like `copy = False` would invalidate other parameters and definitely cause confusion. I'd rather keep it always returning copies, in line with other `get_*` methods.
