### ISSUE TITLE
Filling cell with polygons avoiding overlaps to other layers

### ISSUE THREAD

**Issue by albe-jj** [heitzmann/gdstk#158]
I am currently using positioning filtering to place crosses around my design. 
I would like to have the crosses distributed as uniformly as possible but with position filtering I obtain the following
![image](https://user-images.githubusercontent.com/62503755/227726536-2ea184de-4e71-4f32-a076-8ca3f4d5962e.png)

Is there a more intelligent way to do this? like a fill tool where you can fill certain areas with this crosses making sure they do not overlap with the design but that they fill the space if there is no cross in the radius of say 5 um?

**Comment by joamatab** [comment]
Hi Alberto,

we have fill in gdsfactory, which is build on top of gdstk [see](https://gdsfactory.github.io/gdsfactory/notebooks/04_components_geometry.html#dummy-fill-tiling)

For filling big regions we are building a similar functionality using klayout fill tool
https://github.com/gdsfactory/gdsfactory/issues/1465

**Comment by heitzmann** [comment]
Hi @albe-jj, did you take a look at the second example in the section [Geometry Filtering](https://heitzmann.github.io/gdstk/how-tos.html#geometry-filtering) in the docs? That's a more or less straightforward solution that doesn't require boolean operations. Anything fancier might require specialized algorithms, for example, defining the exact area you want filled through offsetting + boolean operations, simplifying the polygonal boundaries, extracting a Delaunay triangulation and using its centers for the fill placement within a certain size constraint, but that sounds like a lot of overkill depending on your use case.
