### ISSUE TITLE
Segment lengths for FlexPath/RobustPath

### ISSUE THREAD

**Issue by larchen** [heitzmann/gdstk#163]
Is there any way to get the total parametric length of each segment in a flexpath/robust path?

A related question is whether it's possible to get the position and gradient along the segment as a function of the parametrized value for a `FlexPath`, similar to the `position` and `gradient` methods on `RobustPath`?

What I would like to be able to do is to place polygons along a `FlexPath` or a `RobustPath` at a fixed separation over the *entire* path. The current [example](https://heitzmann.github.io/gdstk/how-tos.html#points-along-a-path) in the documentation has a fixed separation between polygons per segment and only works for `RobustPath`.

I could do this with `RobustPath` if there is a way to compute the length of each segment, but I would like to do this with `FlexPath` as well. I'm also open to other suggestions for how to realize the same end result.

**Comment by heitzmann** [comment]
Unfortunately, no. The parameterization we use is within each section for `RobustPath` only. You'd really have to calculate those manually. For `FlexPath` that's just computing the distance between adjacent points in the spine. For `RobustPath` you can be more clever if you know what each section represents and compute their lengths analytically or use the same process: distance between points along the spine. But I see no easy way of back-calculating the parameter `u` used in `gradient` to calculate it. What I would do is build this distance index while constructing the path, that is, for each new section, calculate the new spine and continue calculating the distances from the previous calculations and store the segment number together with the distances. Then you can get `u` for any distance by taking the segment number at that distance and adding the fractional length into that section.
