### ISSUE TITLE
gdstk.text -> How can I change the texttype ?

### ISSUE THREAD

**Issue by EnesBae** [heitzmann/gdstk#164]
In 0.8.1 version
Thanks

T_T

**Comment by heitzmann** [comment]
@EnesBae The [`text`](https://heitzmann.github.io/gdstk/geometry/gdstk.text.html#gdstk.text) function creates text as *Polygons*, so they have `datatype`, not `texttype`. If you want to create textual elements, you're looking for [`Label`](https://heitzmann.github.io/gdstk/library/gdstk.Label.html#gdstk.Label). Those will have a `texttype` you can set.

**Comment by EnesBae** [comment]
Is there a method in the Label function that can generate polygons like the Text function? I want to create polygons that are generated in a different texttype than the default texttype of the Text function.

thanks.

**Comment by heitzmann** [comment]
To be clear, polygons don't have a `texttype` property, their equivalent is `datatype`, and, if you want to set those, it's a simple assignment:
```python
polygon_list = gdstk.text("text string", (0, 0), datatype=1)
# Change the datatype of the first polygon
polygon_list[0]. datatype = 2
```

**Comment by heitzmann** [comment]
To be clear, polygons don't have a `texttype` property, their equivalent is `datatype`, and, if you want to set those, it's a simple assignment:
```python
polygon_list = gdstk.text("text string", (0, 0), datatype=1)
# Change the datatype of the first polygon
polygon_list[0]. datatype = 2
```

The `Label` class represents labels, not polygongs, so it cannot generate geometry by itself. You could write a function that take in a label and uses the `text` function to generate a polygonal representation of that label with any datatype you want.

**Comment by EnesBae** [comment]
The current font used in the text function is not suitable for my field of work. I want to generate polygons with a simpler font that doesn't have diagonal patterns using the text function. Is there any way to do this?
thanks.

**Comment by heitzmann** [comment]
The current font has no diagonal lines. But if you need something specific, there's an example on [how to use any system font](https://heitzmann.github.io/gdstk/how-tos.html#system-fonts).

Beyond that, you'd have to write your own function to convert text into polygons.

**Comment by EnesBae** [comment]
> The current font has no diagonal lines. But if you need something specific, there's an example on [how to use any system font](https://heitzmann.github.io/gdstk/how-tos.html#system-fonts).
> 
> Beyond that, you'd have to write your own function to convert text into polygons.

Perfect !! Thank you so much !!
