### ISSUE TITLE
Increase max_points in boolean operation

### ISSUE THREAD

**Issue by larchen** [heitzmann/gdstk#165]
In gdspy there was the option to specify `max_points` to a larger value in the boolean, offset, etc functions. Would it be possible to have this feature in gdstk as well?

Alternatively is there a way to reverse a fracturing operation and combine a list of polygons into a single polygon?

**Comment by tvt173** [comment]
I believe in gdstk all the fracturing happens at write-time, so there is no need to specify fracturing parameters during these operations. Likewise, if you run an `or` operation on all the shapes in the layer you want to merge, you should be able to "reverse the fracturing operation". You should get the union of shapes back, as explained below.
![image](https://user-images.githubusercontent.com/3070522/230535115-bb91fae7-3a03-4e7c-b15d-fc7abd81ac91.png)

**Comment by heitzmann** [comment]
@larchen Troy is correct, in gdstk those operations do not fracture your polygons, that's why `max_points` doesn't exist there.

**Comment by larchen** [comment]
Thanks for the clarification -- I missed the `max_points` argument for `write_gds` when I was looking at the documentation earlier.
