### ISSUE TITLE
No manylinux wheels since 0.9.38

### ISSUE THREAD

**Issue by isaacwaldron** [heitzmann/gdstk#170]
#168 and/or #169 removed building of manylinux wheels, resulting in releases since 0.9.38 not being supported by binary builds on e.g. RHEL/CentOS 7.9.

**Comment by joamatab** [comment]
Hi Isaac, we can try to bring them back

**Comment by isaacwaldron** [comment]
I pulled forward the definition from 0.9.37 but have no idea how to test it.  See #172

**Comment by joamatab** [comment]
Thank you Isaac,

Jut released v0.9.40

can you try again to see if you can get the wheels in CentOs?

**Comment by isaacwaldron** [comment]
This looks good now, thank you!
