### ISSUE TITLE
Polygon.fracture "never" returns

### ISSUE THREAD

**Issue by nmz787-intel** [heitzmann/gdstk#198]
I found this example which stumps the `fracture` method. It's so "stuck" that I can't even successfully pause my Python debugger (through Pycharm at the moment) to find which line/function of Python code my program was stuck at. I was able to isolate it to the `fracture` method, and for this particular `Polygon`. It isn't failing with more complex (Manhattan) polygons, which is odd to me. Seems like possibly a silly bug, hopefully trivial to find on your end!

```
import gdstk
lib = gdstk.Library()
cell = lib.new_cell('cellname')

p = gdstk.Polygon([[9000., 5000.],
 [5000., 5000.],
 [5000., 7500.],
 [9000., 7500.],
 [9000., 9000.],
 [0., 9000.],
 [0., 3000.],
 [9000., 3000.]])

r = p.fracture(5)   #comment this out, view the OAS, it looks fine, and is a simple shape
print('done)')
cell.add(p)
lib.write_oas('polygon_wont_fracture.oas')
```

I will try to use `slice` in the meantime.

**Comment by heitzmann** [comment]
This should be working now. I believe the new implementation covers all edge cases.
