### ISSUE TITLE
CellArray Attribute

### ISSUE THREAD

**Issue by Ww1206** [heitzmann/gdstk#211]
Gdstk CellArray is not available, and the CellArray attribute of gdspy is better

**Comment by heitzmann** [comment]
`gdstk.Reference` can be used both for single references and arrays. Please take a look at the [tutorial](https://heitzmann.github.io/gdstk/gettingstarted.html#references) and [documentation](https://heitzmann.github.io/gdstk/library/gdstk.Reference.html#gdstk.Reference)

**Comment by Ww1206** [comment]
gdspy CellArray returns colums,rows,rotation,spacing;
gdstk Reference only returns colums,rows. spacing is None, but returns v1 and v2. rotation returns float
