### ISSUE TITLE
There is not function “layoutviewer” in gdstk packages like in gdspy packages？

### ISSUE THREAD

**Issue by Laoshiman42** [heitzmann/gdstk#215]
Hi, sir.
There is not function “layoutviewer” in gdstk packages like in gdspy packages？layout just could be viewed by another software like Klayout after GDS file completed by gdstk package?

**Comment by heitzmann** [comment]
Hi @Laoshiman42, that's correct. Gdstk does **not** include a viewer because the maintenance of a GUI application is too heavy for me to take on my spare time. I've been using KLayout as my deafult viewer for a while and it works great!
