### ISSUE TITLE
proof_lib.gds struct names contain spaces, that makes them illegal cell names in oasis

### ISSUE THREAD

**Issue by stefanottili** [heitzmann/gdstk#220]
RobustPath: scale_width False
RobustPath: scale_width True
FlexPath: scale_width False
FlexPath: scale_width True

klayout by default will convert the "illegal characters" to '*', but it's best practice to avoid these in struct/cellnames

**Comment by lucas-flexcompute** [comment]
Done!

**Comment by heitzmann** [comment]
Done!
