### ISSUE TITLE
Cell.write_svg has incorrect type annotation for shape_style

### ISSUE THREAD

**Issue by FaustinCarter** [heitzmann/gdstk#221]
The type annotation for `shape_style` is `dict[tuple[int, int], str] | None`. However, based on the example in the documentation here (https://heitzmann.github.io/gdstk/library/gdstk.Cell.html#gdstk.Cell.write_svg) it should actually be `dict[tuple[int, int], dict[str, str]] | None`.

**Comment by heitzmann** [comment]
Thanks for reporting!
