### ISSUE TITLE
Polygonal coordinate problem

### ISSUE THREAD

**Issue by SouthChinaHuihuisauce** [heitzmann/gdstk#223]
Hello dear author, I encountered a problem when using gdstk to draw polygons. When obtaining coordinates, it seems that gdstk will also output the defined polygon coordinates. I would like to know how to close it?

![CODE](https://github.com/heitzmann/gdstk/assets/95074184/40b8120d-7a2e-44b9-b19f-d691a896b475)
![RES](https://github.com/heitzmann/gdstk/assets/95074184/bcdbac85-4ac8-4d3b-8d93-53fce95759e3)

**Comment by heitzmann** [comment]
You seem to bee looping over all cells in the library. You probably want to select 1 cell and only display polygons from that cell. In the KLayout screenshot you are only displaying polygons from the NMOS cell (the `get_polygons` function will get polygons from references, so there's no need to loop over cells.)

**Comment by SouthChinaHuihuisauce** [comment]
> You seem to bee looping over all cells in the library. You probably want to select 1 cell and only display polygons from that cell. In the KLayout screenshot you are only displaying polygons from the NMOS cell (the `get_polygons` function will get polygons from references, so there's no need to loop over cells.)

Thank you for your reply. I have resolved the issue through your reply. Thank you

**Comment by SouthChinaHuihuisauce** [comment]
@heitzmann Hello, I would like to ask if there is any GDSTK that can output cell information, similar to Klayout.
![2023-12-18_090943](https://github.com/heitzmann/gdstk/assets/95074184/0099cff9-dd85-4309-8a55-470b10eed347)

**Comment by SouthChinaHuihuisauce** [comment]
@heitzmann Dear author, hello. I have output all cell names, but I don't know how to distinguish the relationship between calls
![gdstk](https://github.com/heitzmann/gdstk/assets/95074184/9e203751-858b-4743-a4c8-0136086520fb)

**Comment by heitzmann** [comment]
@SouthChinaHuihuisauce you have to look into the `references` array for each cell. The cells form a DAG structure that can be traversed if you go through each of the references.

**Comment by SouthChinaHuihuisauce** [comment]
@heitzmann Dear author, first of all, thank you for your reply. I have tried the references you mentioned, but I am not familiar with gdstk and gds files. Can you give me an example?

![coding](https://github.com/heitzmann/gdstk/assets/95074184/44b266e6-79de-49e3-bb75-88cd010e140e)
![log](https://github.com/heitzmann/gdstk/assets/95074184/0adec55e-6541-44a9-994d-a3c5477e59bb)

**Comment by heitzmann** [comment]
You'll probably want to write this as a recursive function. Something like this (in python for brevity):
```
def print_references(cell, indent=""):
    print(indent + "- " + cell.name)
    for reference in cell.references:
        print_references(reference, "    " + indent)
```

**Comment by SouthChinaHuihuisauce** [comment]
@heitzmann  Hello dear author, due to a busy period of time, I apologize for not replying to your message. Recently, I tried the example you provided in Qt and found that there were no references when using cells in C++. Instead, I used the references in cells_ It seems that the array is not quite right. Could you please give me some guidance? Thank you very much.

`void MainWindow::print_references(gdstk::Cell &cell, QString indent)
{
    qDebug() << indent << "-" << cell.name;

    for (size_t i = 0; i < cell.reference_array.count; i++) {
        print_references(*cell.reference_array[i], "    " + indent);
    }
}`
![2](https://github.com/heitzmann/gdstk/assets/95074184/224b17a9-bf02-4a85-a795-d9d8c73aec6c)

**Comment by SouthChinaHuihuisauce** [comment]
![3](https://github.com/heitzmann/gdstk/assets/95074184/6d0dbfa4-b80f-4123-9614-27a90a45e89f)

**Comment by SouthChinaHuihuisauce** [comment]
@heitzmann Thank you very much for your sample code. We have found it
