### ISSUE TITLE
Memory allocation using regular repetitions.

### ISSUE THREAD

**Issue by arondahl** [heitzmann/gdstk#224]
Hi,

I noticed there is a large disparity of memory use, when generating reference repetitions using perpendicular v1&v2 vectors in gdstk.Repetition() versus using vectors, which are not perpendicular. I was wondering why this is and also whether there is a work around?

Best,
Aron Dahlberg

**Comment by heitzmann** [comment]
Are you talking about runtime memory usage or the size of the resulting GDSII file? Both are expected to be larger in the non-orthogonal case, but the largest difference will be in the saved file, because the GDSII format does not support this type of array.

**Comment by heitzmann** [comment]
Yes, in that case you have to use the OASIS format to see any gain.
