### ISSUE TITLE
Pin Identification and Extraction

### ISSUE THREAD

**Issue by Rishabhgoyal07** [heitzmann/gdstk#229]
@heitzmann , How can we identify the pins that are present in the leaf cells (bottom hierarchy) of a layout, and export them to the top level of the layout?? Is this possible in gdstk?

**Comment by heitzmann** [comment]
How are the pins represented? There's no "pin" object in GDSII files. If they are paths or polygons, you can use `get_polygons` with the appropriate layer/datatype info. If they are nodes, gdstk doesn't have support for those, unfortunately.

**Comment by Rishabhgoyal07** [comment]
I have created a **label** using the ### Label class, but when i am using the **cell.labels function** to get all the labels of a cell, the **created label** is not coming in the list, also when i am viewing my cell in cadence virtuoso, there also it is not getting recognized, why is this happening??

**Comment by Rishabhgoyal07** [comment]
Thank you for your help, also i want to know how can we **flip a cell horizontally,** i..e we the **left side of the cell** becomes the **right side and the right side becomes the left side.**

**Comment by heitzmann** [comment]
You can use a reference setting `rotation=180` and `x_reflection=True`.

**Comment by Rishabhgoyal07** [comment]
I did that, but the quadrant in which the cells is, got changed from **1 to 4 quadrant**, i..e the x-axis is changed from **x to-x**. Is there any way so that the x-axis doesn't get changed, i..e, the **cell is mirrored in its place only**?

**Comment by nmz787-intel** [comment]
> I am viewing my cell in virtuoso, in virtuoso we can directly create a pin on any metal, while the created pin using gdstk is not getting recognized in virtuoso.

You need to use the appropriate options during `strmin` or `oasisin`, such as `-objectMap` or `-pinAttNum`, or write `SKILL` or `OaScript` code to find your `Labels` on your `metal:pin` layer:type and then convert them into Pin objects
