### ISSUE TITLE
Create a new python package that have the latest updates

### ISSUE THREAD

**Issue by atorkmabrains** [heitzmann/gdstk#235]
Hi @heitzmann and @joamatab,

Could you please create a new version for the gdstk that would include the latest updates that were included in the following PR: https://github.com/heitzmann/gdstk/pull/231 ?

Regards,
Amro

**Comment by atorkmabrains** [comment]
@heitzmann and @joamatab ?

**Comment by heitzmann** [comment]
It's already been released last month: https://github.com/heitzmann/gdstk/releases/tag/v0.9.50

**Comment by atorkmabrains** [comment]
Perfect
