### ISSUE TITLE
0.9.51: Doesn't install include directory and .pc file

### ISSUE THREAD

**Issue by yurivict** [heitzmann/gdstk#245]
These lines disappeared:
```
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/gdstk.pc DESTINATION ${CMAKE_INSTALL_LIBDIR}/pkgconfig)
CONFIGURE_FILE("gdstk.pc.in" "gdstk.pc")
```

This line also disappeared:
```
include(GNUInstallDirs)
```
It probably installed the ```include``` directory.

**Comment by heitzmann** [comment]
That's right, the whole build system changed because there were too many hacks. The gdstk.pc was one of them. It was not properly created and was starting to break on Windows.

The headers I forgot to check after the changes, but I've put them back in the latest commit.

**Comment by yurivict** [comment]
Do you intend to make a corrected release?

**Comment by heitzmann** [comment]
Sorry, I thought I had already released this... I've prepared the release locally and completely forgot to push!
