### ISSUE TITLE
If adding a reference cell, why it is necessary to add this cell instance in lib???

### ISSUE THREAD

**Issue by huangwenjunlovedy** [heitzmann/gdstk#249]
I found that when using a reference cell, it is necessary to add the instance of the reference cell to the lib, otherwise it will fail. May I ask why this is happening? I think if a top-level cell is added to the lib, then the referenced cells contained in that top-level cell will be included together in the lib. But in reality, it's not like that. I hope you can answer, thank you!

my code: 
[test2.zip](https://github.com/heitzmann/gdstk/files/15397496/test2.zip)

（1）When lib adds instances that reference cells :
![image](https://github.com/heitzmann/gdstk/assets/20516638/dd1b389b-93c3-4642-b297-64d2fab143a9)

![image](https://github.com/heitzmann/gdstk/assets/20516638/972d97fe-97e7-41a4-8564-7b98be8b7231)

（2）When lib does not add an instance referencing cell :
![image](https://github.com/heitzmann/gdstk/assets/20516638/aab1a3dc-0a08-491d-af01-ea1fc879d27b)
![image](https://github.com/heitzmann/gdstk/assets/20516638/681c11e6-89da-4c66-8342-6b7f0020ff6a)

**Comment by heitzmann** [comment]
That's the expected behavior. That was a design choice made in early development, because it is quite easy to simply replace your line with `lib2.add(main, *main.dependencies())` and have the automatic behavior you desire.

**Comment by nmz787-intel** [comment]
I believe it has to do with some tools that have many GDS files, and can load them all as a distributed library. This is an assumption though, and may be an incorrect interpretation of behavior I see in closed-source tools.
