### ISSUE TITLE
Any plan for supporting sub-classing?

### ISSUE THREAD

**Issue by treygreer** [heitzmann/gdstk#25]
It appears that the Cell class cannot be used as a base class.  I did enjoy the ability to subclass Cells in gdspy.  Any chance of this returning in gdstk?  Is this something I could help with?  I assume it has something to do with the new 'thin' python approach.  Thanks for a wonderful resource! 

> class EulerRing(gdstk.Cell):
> TypeError: type 'gdstk.Cell' is not an acceptable base type
>

**Comment by heitzmann** [comment]
@treygreer I believe this should work with a minor flag addition in the type definitions. I included in the latest commit if you want to try it out.
