### ISSUE TITLE
QH6412 & QH6235 ERROR when gds file is huge

### ISSUE THREAD

**Issue by Larson-Li** [heitzmann/gdstk#251]
QH6235 qhull error (qh_memalloc): negative  request size (-1633304992). Did int overflow due to high-D?

QH6412 qhull input error (qh_initqhull_globals): expecting between 1 and 2147483631 points. Got 2147483646 2-d points

**Comment by Larson-Li** [comment]
@heitzmann

**Comment by heitzmann** [comment]
Thanks for the report @Larson-Li. I've fixed the maximum number of points allowed in qhull. It should be working for this commit. Would you be able to confirm the fix?
