### ISSUE TITLE
How to simply calculate the coordinates of the graph in a certain sub-cell in the top cell?

### ISSUE THREAD

**Issue by tjl0209** [heitzmann/gdstk#258]
In the design of the semiconductor industry, we need to extract multiple coordinates of certain cells containing mark in the top cell (we know that these marks are included in the top cell, but they may be multi-level). This is very important for the subsequent manufacturing. Does gdstk have a way to achieve this function simply?

**Comment by frankxu-omni** [comment]
Is this what you want?
top_cell.get_labels()
top_cell.get_polygons()

**Comment by tjl0209** [comment]
> Is this what you want? top_cell.get_labels() top_cell.get_polygons()



> Is this what you want? top_cell.get_labels() top_cell.get_polygons()

**Comment by tjl0209** [comment]
> Is this what you want? top_cell.get_labels() top_cell.get_polygons()
![微信截图_20240702213332](https://github.com/heitzmann/gdstk/assets/174242368/0eebb80d-606d-45fb-90a1-87c306a39615)
Thank you for your reply! Although this doesn't seem to be what I want. I used a diagram to simply elaborate my requirement.
