### ISSUE TITLE
Unnecessary dependency on oldest-supported-numpy

### ISSUE THREAD

**Issue by wshanks** [heitzmann/gdstk#260]
oldest-supported-numpy was intended to be used as a build dependency before numpy 2 (which has backwards ABI compatibility). It should not be needed as a runtime dependency (just numpy). Also, since gdstk dropped support for Python 3.8, oldest-supported-numpy should not be needed as a build dependency either.

**Comment by daquinteroflex** [comment]
@heitzmann I think this might be related to the poetry resolution issue too https://github.com/flexcompute/tidy3d/pull/1913 according to https://github.com/python-poetry/poetry/issues/8830 and hence the unclear error on the lockfile resolution in https://github.com/python-poetry/poetry/issues/9659 for an empty project with numpy and gdstk as a dependency.

Suspect a new release with this change sounds like it might solve this environment issue. What do you think?

**Comment by heitzmann** [comment]
The newest release already includes this fix. 'oldest-supported-numpy' has
already been removed, or did I forget anything else?

**Comment by daquinteroflex** [comment]
Hi Lucas,

![image](https://github.com/user-attachments/assets/d80a8709-1a98-410d-94f1-9d37a39eec55)

I'm just going from this commit history, seems like this PR was merged after the 0.9.53 tag?

**Comment by heitzmann** [comment]
My bad, I was assuming these changes had already been released! I've
triggered a new version release right now to include them.

**Comment by daquinteroflex** [comment]
Thanks a lot Lucas! Indeed the poetry lockfile resolution is now working properly with this release
