### ISSUE TITLE
Method to Find Cell Hierarchy by Coordinate

### ISSUE THREAD

**Issue by gambino19** [heitzmann/gdstk#27]
Are there any methods recommended or supported to find direct hierarchy path (i.e from top cell to leaf cell) from a provided coordinate? My thought was recursively searching through reference bounding_box ranges with respect to reference origin.

**Comment by heitzmann** [comment]
@gambino19 Yes, that would be my first guess as well. There's no built-in function for this type of query.

**Comment by gambino19** [comment]
Ok, thank you for the response.
