### ISSUE TITLE
install gdstk on mac through  conda forge

### ISSUE THREAD

**Issue by worldsheep** [heitzmann/gdstk#34]
I tried to install gdstk following the instructions in: [https://github.com/conda-forge/gdstk-feedstock](https://github.com/conda-forge/gdstk-feedstock) but I get the following message in my terminal:

```
conda install gdstk
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for bleach sphinx dask distributed nbconvert _ipyw_jlab_nb_ext_conf pytest jupyterlab astropy numpydoc pip wheel spyd-
```

The examining conflict part is taking forever and I ended up aborting. Has anyone encountered the same problem?

I have just installed anaconda and I am running version: 1.10.0

P.s. I have been using gdspy so far. It is great, thanks for the great work and for sharing! I look forward  to using gdstk.

**Comment by heitzmann** [comment]
@worldsheep Could it be an incompatibility due to numpy from different channels? Please take a look at https://github.com/conda-forge/gdstk-feedstock/issues/2 to see if it helps. Otherwise, would you mind opening this issue in the conda-forge recipe repo?

**Comment by worldsheep** [comment]
Unfortunately, I couldn't find a solution. I'll open this issue on the conda-forge recipe repo!

**Comment by heitzmann** [comment]
Thanks, I'll close this one and follow up over there.
