### ISSUE TITLE
Parametric widths for RobustPath

### ISSUE THREAD

**Issue by mdaal** [heitzmann/gdstk#37]
This is an enhancement request.

For gdstk.RobustPath, would it be possible to implement  parametric widths for parametric sections? You had this implemented in gdspy. 

As a related remark, It looks like you have begun to implement  callable path_gradient argument for parametric in the code, but its not yet in the documentation. What is your plan for callable path_gradient?

Thanks. Great package, as  always!
Miguel

**Comment by heitzmann** [comment]
@mdaal Thanks for the heads up! It was only the docstring that was copied from `FlexPath` and did not reflect the actual code… it should be fixed now. Parametric widths and offsets were already supported!
