### ISSUE TITLE
Catch negative width argument passed to FlexPath

### ISSUE THREAD

**Issue by jsbangsund** [heitzmann/gdstk#39]
I recently accidentally passed a negative width argument to FlexPath, which crashed the kernel and didn't return any errors. I don't know what is preferred, but it seems like this could be fixed a few ways:

1. Assert that width>0, throw back error to user if width<0 or any([w<0 for w in widths])
2. Take the absolute value of width and if width<0, warn the user that the absolute value was taken

**Comment by heitzmann** [comment]
@jsbangsund I believe the library is missing all sorts of checks of this kind. I'll leave this issue open as an enhancement so that I can progressively go over the whole code base looking for such instances. Thanks for pointing it out!
