### ISSUE TITLE
About open this package

### ISSUE THREAD

**Issue by doublewei6** [heitzmann/gdstk#43]
Hi, 
I am sorry for wasting your time.
I do not know how to open this package, which IDE I need to use, or can I open this package using visual studio 2019

**Comment by heitzmann** [comment]
@doublewei6 No problem at all.

This is not a “package”, though. It is a C++ library with a Python wrapper. If you want to use it from C++, you can just add the source files to your project and copile it statically. The CMakeLists.txt can be used as an example as to how to install it system-wide for dynamically or statically linked versions.

To use it from Python, follow the installation instructions for Windows in the README. You'll need to have Conda installed first.
