### ISSUE TITLE
Is there any way to use LayoutViewer function as in gdspy

### ISSUE THREAD

**Issue by runck** [heitzmann/gdstk#46]
Hi, 
I used to use gdspy with LayoutViewer, but I can not find similar function in gdstk. Is this function be replaced, or just deleted? 
Thank you!

**Comment by heitzmann** [comment]
@runck There's no replacement indeed. LayoutViewer was very inefficient for larger layouts, and I have no plans to reimplement it, at least for now. I recommend using, for example, Klayout, which can detect file changes and reload the layout when you make any changes and save it.

**Comment by runck** [comment]
Thank you for your recommendation. I am trying it.
