### ISSUE TITLE
read_oas returns emtpy library

### ISSUE THREAD

**Issue by ChristianWieden** [heitzmann/gdstk#48]
Hello,

when trying to read in a oasis file which i freshly created with klayout and only contains a single box item, then the returned library from gdstk is empty.
This happens in c++ and python.

```
Python:
>>> lib2=gdstk.read_oas("/home/wieden/test.oas")
>>> lib2.top_level()
[]
>>> lib2.cells
[]
```
[test.zip](https://github.com/heitzmann/gdstk/files/6754666/test.zip) (can't attach .oas file directly so i zipped it)

I use RedHat 7 with Python 3.6.8.
gdstk version 0.6
I installed gdstk via python setup.py install, because the system could not install it via conda.

**Comment by heitzmann** [comment]
Thanks for reporting, @ChristianWieden! I'll investigate the issue.
