### ISSUE TITLE
Cannot reference static library

### ISSUE THREAD

**Issue by xunZeng** [heitzmann/gdstk#57]
Hello, I used cmake to build the gdstk code, and successfully generated gdstk.lib and a series of header files. However, when I referenced the static library in a new project(created by visual studio 2019, windows 10), the problem occurred that the external symbols could not be resolved.

**Comment by heitzmann** [comment]
Which symbols are not found? You also need to link against lapack and zlib, did you do that?

**Comment by xunZeng** [comment]
Indeed, I failed to link lapack correctly. My problem is solved, thank you very much.
