### ISSUE TITLE
Newbie question incoming : "gdstk.h No such file or directory"

### ISSUE THREAD

**Issue by mark-fein** [heitzmann/gdstk#89]
Hello, I am pretty new to C++ overall and am having some trouble generating the initial red rectangle in gdstk. I have copy-pasted source code below into a "Hello World" default Project in Eclipse but am getting the above error. I assume its because I need to "point" or include the referenced header file or somewhere include it in list of things to look [in binaries for (much like <iostream> and <stdio.h> live)].

![image](https://user-images.githubusercontent.com/91111307/164510870-b2bb09a7-9d07-4d4a-818b-a63f73319e0d.png)

![image](https://user-images.githubusercontent.com/91111307/164510617-66f42c43-b743-4684-a56e-6194b1ae2758.png)

**Comment by mark-fein** [comment]
Associated SE Thread over here as well [Linky](https://stackoverflow.com/questions/71958229/newbie-question-incoming-gdstk-h-no-such-file-or-directory)

**Comment by heitzmann** [comment]
@mark-fein You can use CMake to build and install gdstk as a shared/dynamic library and configure your eclipse project to link to the installed version of gdstk and find the installed header (gdstk.h).

**Comment by mark-fein** [comment]
I have successfully installed/built it here: C:\msys64\home\me\projects\gdstk with following files. Now do I run from Anaconda prompt or within a C++ IDE?

![image](https://user-images.githubusercontent.com/91111307/165137115-ab419956-1e5b-4fae-9594-16236a0b8e39.png)

Thanks for all the help so far

**Comment by mark-fein** [comment]
> Tried that (as alluded to in post) however I now get the following error:
> 
> ```
> markfein124@l-ul71kght6q MINGW64 ~/projects/gdstk
> $ cmake -S . -B build -G"MSYS Makefiles"
> CMake Error: Could not create named generator MSYS Makefiles
> 
> Generators
> * Unix Makefiles               = Generates standard UNIX makefiles.
>   Ninja                        = Generates build.ninja files.
>   Ninja Multi-Config           = Generates build-<Config>.ninja files.
>   CodeBlocks - Ninja           = Generates CodeBlocks project files.
>   CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
>   CodeLite - Ninja             = Generates CodeLite project files.
>   CodeLite - Unix Makefiles    = Generates CodeLite project files.
>   Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
>   Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
>   Kate - Ninja                 = Generates Kate project files.
>   Kate - Unix Makefiles        = Generates Kate project files.
>   Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
>   Sublime Text 2 - Unix Makefiles
>                                = Generates Sublime Text 2 project files.
> ```
> 
> Thoughts?

I fixed this. See comment below

**Comment by heitzmann** [comment]
How did you compile? Do you have a log of the compilation messages? Compiling on windows is troublesome. If you used Anaconda for compilation, you should have the python interface working. On the Anaconda prompt you can try `python -c "import gdstk"` to see if any errors show up.

To use with C++ you'll have to compile with cmake and check where it installs header files and the resulting lib on Windows. In your IDE you'll have to configure your project to find those files.

**Comment by mark-fein** [comment]
These are the header files, correct?

![image](https://user-images.githubusercontent.com/91111307/165138868-1e3832bf-40d5-4bde-ba88-aabaeb5e4619.png)
These are in the a copy-able path. How to add this to a project in IDE (say eclipse) or another (if you have one you prefer)?

**Comment by mark-fein** [comment]
> How did you compile? Do you have a log of the compilation messages? Compiling on windows is troublesome. If you used Anaconda for compilation, you should have the python interface working. On the Anaconda prompt you can try `python -c "import gdstk"` to see if any errors show up.
> 
> To use with C++ you'll have to compile with cmake and check where it installs header files and the resulting lib on Windows. In your IDE you'll have to configure your project to find those files.

Tried in Anaconda prompt and showed no error as far as I can tell

![image](https://user-images.githubusercontent.com/91111307/165139433-62ffd819-3c87-4202-8a68-a80c4110b081.png)

**Comment by heitzmann** [comment]
I don't use an IDE—I can't help you there, sorry. On the command line it's just a flag.

Your python interface seems to be working correctly.

**Comment by mark-fein** [comment]
Is there any preference to running in python vs c++?

**Comment by heitzmann** [comment]
@mark-fein Sorry for taking so long to reply. I missed your last comment.
In C++ you gain in efficiency. For large layouts, it can be a huge advantage. However, you'll be responsible for memory management, which adds complexity. If you're comfortable with C, it shouldn't be a problem.
The advantage of using Python is the easy of quickly prototyping and iterating over different layouts.
