### ISSUE TITLE
question add attributes to gdstk.Cell objects

### ISSUE THREAD

**Issue by frankxxu** [heitzmann/gdstk#92]
Hi Heitzmann,
We want to be able to assign new attributes (width, height) to a gdstk.Cell object.  we scan a gdstk.Cell object for a special layer:datatype rectangle. Then we calculate width and height to the gdstk.Cell object.  

cella = gdstk.Cell('cella')
cella.width=10.0
cella.height=20.0

 It does not work. Is there a way to achieve this?
Thanks,
Best regard,
-Frank

**Comment by heitzmann** [comment]
Unfortunately no. The instaces are locked for inclusion of new attributes (similarly to defining the `__slots__` attribute in a python class.

**Comment by frankxxu** [comment]
Thanks, I will work around it then.
Best regard,
-Frank
