### ISSUE TITLE
How to calculate the graphic area in a GDS file

### ISSUE THREAD

**Issue by Estazolam7** [heitzmann/gdstk#94]
I get a library after importing a GDS file by the 'gdstk.read_gds' command. Then I can not get a 'cell' type data from the library. But the 'area' command can only work for a 'cell' type data, so I can not calculate the graphic area. I wonder if there is a method. Many thanks!

**Comment by heitzmann** [comment]
After reading the file, you can access all cells in the library through [`Library.cells`](https://heitzmann.github.io/gdstk/library/gdstk.Library.html#gdstk.Library.cells)

**Comment by Estazolam7** [comment]
> After reading the file, you can access all cells in the library through [`Library.cells`](https://heitzmann.github.io/gdstk/library/gdstk.Library.html#gdstk.Library.cells)

It works! I made some mistakes when using the 'Library.cells' command yesterday. Thank you very much!
