### ISSUE TITLE
Library Compilation Error

### ISSUE THREAD

**Issue by GimliAlban** [heitzmann/gdstk#99]
Hello,

I'm new to the tool and I am trying to compile the library in python (ie: python3 setup.py install)

In the file clipper_tools.cpp, during the compilation (vscode is also flagging the error) I have this error:
`no operator "=" matches these operandsC/C++(349)
clipper_tools.cpp(167, 23): operand types are: __gnu_cxx::__normal_iterator<ClipperLib::IntPoint *, std::vector<ClipperLib::IntPoint, std::allocator<ClipperLib::IntPoint>>> = void`

I'm not sure what's causing that, I don't do cpp code. Can you help me there?

Best

**Comment by heitzmann** [comment]
Could #63 be related? What version of gcc are you using?

**Comment by heitzmann** [comment]
It should return an iterator starting from C++11, which is the standard we're targeting: https://en.cppreference.com/w/cpp/container/vector/insert
